# Generated by Django 5.0.3 on 2024-03-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0007_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
