# Generated by Django 5.0.3 on 2024-04-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0010_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_email',
            field=models.EmailField(max_length=255),
        ),
    ]
