# Generated by Django 5.0.3 on 2024-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekermodule', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='additional_documents/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='personal_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='work_history',
            field=models.TextField(blank=True),
        ),
    ]
